export const MOCK_POOLS = [
  {
    poolId: '1',
    daoId: '1',
    name: 'Consensus Quest',
    description: 'Collective Decisions',
    createdAt: new Date('2024-01-15'),
    assetAddress: '0x...',
    currentBalance: 2.5,
    status: 'active' as const,
    apy: 12.5,
    risk: 'medium' as const,
    avatar: '👥',
  },
  {
    poolId: '2',
    daoId: '1',
    name: 'Community Creators',
    description: 'Decentralized Investment',
    createdAt: new Date('2024-01-10'),
    assetAddress: '0x...',
    currentBalance: 1.8,
    status: 'active' as const,
    apy: 8.3,
    risk: 'low' as const,
    avatar: '🎨',
  },
  {
    poolId: '3',
    daoId: '1',
    name: 'Collective Contract',
    description: 'Smart Contracts',
    createdAt: new Date('2024-01-20'),
    assetAddress: '0x...',
    currentBalance: 3.2,
    status: 'active' as const,
    apy: 15.7,
    risk: 'high' as const,
    avatar: '⚡',
  },
  {
    poolId: '4',
    daoId: '1',
    name: 'Complex Collective',
    description: 'Governance Network',
    createdAt: new Date('2024-01-25'),
    assetAddress: '0x...',
    currentBalance: 4.1,
    status: 'active' as const,
    apy: 10.2,
    risk: 'medium' as const,
    avatar: '🔗',
  },
  {
    poolId: '5',
    daoId: '1',
    name: 'Automated Yield Pool',
    description: 'Daily Automated Strategies',
    createdAt: new Date('2024-02-01'),
    assetAddress: '0x...',
    currentBalance: 5.3,
    status: 'active' as const,
    apy: 18.9,
    risk: 'high' as const,
    avatar: '🤖',
  },
];

export const MOCK_CHART_DATA = [
  { time: '1d', value: 2.5 },
  { time: '2d', value: 2.7 },
  { time: '3d', value: 2.4 },
  { time: '4d', value: 2.9 },
  { time: '5d', value: 3.1 },
  { time: '6d', value: 2.8 },
  { time: '7d', value: 3.3 },
  { time: '8d', value: 3.5 },
  { time: '9d', value: 3.2 },
  { time: '10d', value: 3.7 },
  { time: '11d', value: 3.9 },
  { time: '12d', value: 3.6 },
  { time: '13d', value: 4.1 },
  { time: '14d', value: 4.3 },
];
